# For more information look at "README.md".

# GLOBAL SITE SETTINGS
# Parameters used by HUGO to configure the site's global settings.
preserveTaxonomyNames = "true"

baseurl = "https://delias-cleaning.com/"
languageCode = "en-us"
title = "Delia's Cleaning"
theme = "hugo-myportfolio-theme"

[markup.goldmark.renderer]
unsafe= true

[params]

    # GENERAL SITE PARAMETERS
    # Parameters used by the site at the global level.

    # File(s) containing overriden CSS variables (can have more than 1) (OPTIONAL)
    custom_css = [ "custom.css" ]

    # ----------

    # SITE METADATA
    # Parameters used to configure metadata in the HTML "head" section.

    [params.meta]
        # To provide some metadata for search engines (OPTIONAL)
        author = "Joel Guerra"
        description = "Delia's Cleaning"

        # The path must be relative to the static folder (MANDATORY)
        favicon = "favicon-32x32.png"

    # ----------

    # HOMEPAGE
    # Define the sections and the order in which they appear (MANDATORY)
    [params.homepage]
        sections = [ "home", "about", "services", "contact" ]

    # ----------

    # NAVIGATION MENU
    # Define the navigation bar entries and the order in which they appear (OPTIONAL)
    [params.navigation]

        # Brand (OPTIONAL - but required if want HOME button)
        brand = "DELIA'S CLEANING"

        # NAVIGATION MENU ENTRIES (OPTIONAL)
        # Add an entry for each section to add in the navigation menu.
        # Syntax:
        #    key = "<VALUE>"
        #    => Where
        #        - "key" is in:
        #            - about
        #            - services
        #            - skills
        #            - projects (! - SPECIAL CASE: DIFFERENT MANAGEMENT THAN OTHER SECTIONS!)
        #            - contact
        #
        #        - "<VALUE>" is the string to display as menu item.
        # If no entry is specified => No navigation menu is created.
        #    (even if "params.navigation.links" is defined, but empty)
        # => Can define a dummy variable in "links" to force the creation of the menu (e.g.: dummy = 1).
        # To change order, need to change code in navigation menu creation.
        # Special case: "projects".
        #    projects = [ { section = "<SECTION_DIRECTORY>", label = "<VALUE>" }, ... ]
        # ! - Values for "sections" in "projects" must be the same as used in "projects.params".
        # (& must correspond to the section directories)
        
        [params.navigation.links]
            about    = "ABOUT"
            services = "SERVICES"
            contact  = "CONTACT"

    # ----------

    # PAGE 404
    [params.page404]
        text = "OOPS, PAGE NOT FOUND!"
        background_image = "404.jpg"
        button_text = "BACK HOME"
